name: Linux Clang Build
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Declare Git Variables
        id: git_vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Install dependencies
        run: bash ./install_linux_requirements.sh
      - name: CMake Config Debug
        run: cmake --preset linux-clang-debug
      - name: Cmake Build Debug
        run: cmake --build --preset linux-clang-debug --target install
      - name: CMake Config Release
        run: cmake --preset linux-clang-release
      - name: Cmake Build Release
        run: cmake --build --preset linux-clang-release --target install
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: tormenta-linux-clang-${{ steps.git_vars.outputs.sha_short }}
          path: out
          retention-days: 5